---
environment: production
chdir: /opt/engines/src/server
address: 0.0.0.0
port: 4567
pid: /home/engines/run/system.pid
log: /var/log/system_server.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: false
