--- !ruby/object:ManagedService
container_name: pgsql_server
publisher_namespace: EnginesSystem
type_path: database/sql/pgsql
ctype: service
persistent: true
last_error: 
memory: '160'
hostname: pgsql
domain_name: 
environments: []
image: engines/pgsql:_Engines_System(release)
volumes:
 pg_database: !ruby/object:Volume
  name: pg_database
  remotepath: "/var/lib/postgresql/"
  localpath: "/var/lib/engines/pgsql"
  mapping_permissions: "rw"
 sslcerts: !ruby/object:Volume
  name: sslcerts
  remotepath: "/etc/ssl/"
  localpath: "/opt/engines/etc/pgsql/ssl/"
  mapping_permissions: "ro"
port: 
mapped_ports:
- !ruby/object:WorkPort
  name: pgsql
  port: 3306
  publicFacing: false
  external: 0
repo: na
last_result: 
setState: nocontainer
nginxored: false
conf_register_site: false
conf_register_dns: true
conf_self_start: true
dependant_on:
- "dns"