--- !ruby/object:ServiceManager
containerName: servicemanager
publisher_namespace: EnginesSystem
type_path: servicemgr
ctype: service
conf_self_start: true
last_error: 
memory: '16'
hostName: servicemanager
domainName: 
environments: [] 
image: _Engines_System(flavor)fs:alpha
volumes: 
eports: []
repo: na
last_result: |
  b06184ef59759baec2c7bb6a854c9d529cfa47eda9fa9d4e95c8ac27f6da424c
setState: nocontainer
nginxored: false
databases: []
conf_register_site: false
conf_register_dns: true