--- !ruby/object:ManagedService
container_name: nginx
publisher_namespace: EnginesSystem
type_path: nginx
ctype: service
persistent: false
publisher_namespace: EnginesSystem
type_path: nginx
last_error: 
memory: '80'
hostname: nginx
domain_name: 
environments: []
image: _Engines_System(flavor)/nginx:_Engines_System(release)
volumes:
 sslcerts: 
  name: sslcerts
  remotepath: "/etc/nginx/ssl/"
  localpath: "/var/lib/engines/cert_auth/services/nginx/"
  permissions: "ro"
 var_run: 
  name: var_run
  remotepath: "/var/run/nginx"
  localpath: "/opt/engines/run/services/nginx/run/nginx"
  permissions: "rw" 
port: 
mapped_ports:
 https:
  name: https
  port: 4430
  publicFacing: true
  external: 443
 http: 
  name: http
  port: 8000
  publicFacing: true
  external: 80
repo: na
last_result: 
setState: running
nginxored: false
conf_register_site: false
conf_register_dns: true
conf_self_start: true
dependant_on:
- "dns"
