--- !ruby/object:ManagedService
container_name: syslog
publisher_namespace: EnginesSystem
type_path: syslog
ctype: service
persistent: false
last_error: 
memory: '32'
hostname: asyslog
domain_name: 
environments: []
image: engines/syslog:_Engines_System(release)
volumes:
 config: !ruby/object:Volume
  name: config
  remotepath: "/etc/syslog-ng/conf.d/"
  localpath: "/opt/engines/etc/syslog/conf/"
  mapping_permissions: rw
 logs: !ruby/object:Volume
  name: config
  remotepath: "var/log/rmt/"
  localpath: "/var/lib/engines/syslog/rmt/"
  mapping_permissions: rw
port: 
mapped_ports:
repo: na
last_result: 
setState: running
nginxored: false
conf_register_site: false
conf_register_dns: true
conf_self_start: true
dependant_on:
- "dns"