--- !ruby/object:ManagedService
cont_user_id: 22034
container_name: radius
publisher_namespace: EnginesSystem
type_path: radius
ctype: service
persistent: true
conf_self_start: true
shareable: false
last_error: 
memory: '128'
hostname: radius
domain_name: engines.internal
host_network: false
soft_service: false
environments: []
kerberos: true
mapped_ports:
 radius:
  name: radius
  port: 1812
  publicFacing: false
  external: 1812
image: _Engines_System(flavor)/radius:_Engines_System(release)
volumes: 
environments: 
repo: na
last_result: 
setState: running
nginxored: false
conf_register_site: false
conf_register_dns: true
dependant_on:
- "ldap"

