--- !ruby/object:ManagedService
container_name: mgmt
ctype: service
persistent: true
last_error: 
memory: '512'
hostname: mgmt
publisher_namespace: EnginesSystem
type_path: mgmt
port: 8484
domain_name: _Engines_System(default_domain)
volumes: 
 certs: 
  volume_name: certs
  remotepath: "/opt/engines/etc/ssl/"
  localpath: "/var/lib/engines/cert_auth/services/mgmt/"
  permissions: "ro"  
 public_dir: 
  volume_name: public_dir
  remotepath: "/home/fs/persistent"
  localpath: "/var/lib/engines/mgmt/public"
  permissions: "rw"  
mapped_ports:
 web:
  name: web
  port: 8001
  publicFacing: true
  external: 8484
  proto_type: tcp
environments:
- !ruby/object:EnvironmentVariable
 name: SYSTEM_API_URL
 value: https://_Engines_System(docker_ip):2380
 has_changed: true 
 build_time_only: false
 immutable: false
 label: "Local System"
- !ruby/object:EnvironmentVariable 
 name: SYSTEM_RELEASE
 value: _Engines_System(release)
 has_changed: true 
 build_time_only: false
- !ruby/object:EnvironmentVariable 
 name: ACTION_CABLE_ALLOWED_REQUEST_ORIGINS
 value: https://mgmt._Engines_System(default_domain):8484
 has_changed: true 
 build_time_only: false
- !ruby/object:EnvironmentVariable 
 name: ACTION_CABLE_URL
 value: wss://mgmt._Engines_System(default_domain):8484/
 has_changed: true 
 build_time_only: false
- !ruby/object:EnvironmentVariable 
 name: RAILS_LOG_TO_STDOUT
 value: true
 has_changed: true 
 build_time_only: false
- !ruby/object:EnvironmentVariable
 name: FQDN_PORT
 value: mgmt._Engines_System(default_domain):8484
 has_changed: true 
 build_time_only: false
 immutable: false
 label: "FQDN_PORT"
- !ruby/object:EnvironmentVariable
 name: DOMAIN
 value: _Engines_System(default_domain)
 has_changed: true 
 build_time_only: false
 immutable: false
 label: "DOMAIN"
image: engines/mgmt:_Engines_System(release)
repo: na
last_result: 
setState: nocontainer
nginxored: false
conf_register_site: true
conf_register_dns: true
conf_self_start: true
dependant_on:
- 'dns'
- 'syslog'
- 'redis'