--- !ruby/object:ManagedService
cont_user_id: 22025
container_name: dhcpd
publisher_namespace: EnginesSystem
type_path: dhcpd
ctype: service
persistent: false
conf_self_start: true
last_error: 
memory: '16'
hostname: dhcpd
domain_name: 
kerberos: false
environments: []
image: _Engines_System(flavor)/dhcpd:_Engines_System(release)
volumes: {}
mapped_ports:
 dhcpd:
  name: dhcpd
  port: 67
  publicFacing: true
  proto_type: udp
  external: 67
repo: na
last_result: 
setState: nocontainer
nginxored: false
conf_register_site: false
conf_register_dns: true
