--- !ruby/object:NagiosService
containerName: monit
ctype: service
last_error: 
memory: '32'
hostName: monit
domainName: test
environments: []
image: _Engines_System(flavor)/nagios
volumes: 
port: 80
eports: []
repo: na
last_result: |
  monit
setState: running
databases: []
registerSite: true
monitored: false
conf_register_site: true
conf_register_dns: true
