--- !ruby/object:VolumeService
publisher_namespace: EnginesSystem
type_path: filesystem/local/filesystem
container_name: volmanager
ctype: service
persistent: true
conf_self_start: true
last_error: 
memory: '16'
hostname: volmanager
domain_name: 
environments: []
image: engines/fs:_Engines_System(release)
volumes: 
 fs_rw: !ruby/object:Volume
  name: fs_rw
  remotepath: "/var/fs/local/"
  localpath: "/var/lib/engines/fs/"
  mapping_permissions: "rw"
mapped_ports: []
repo: na
last_result:
setState: running
nginxored: false
conf_register_site: false
conf_register_dns: true
conf_self_start: true