--- !ruby/object:VolumeService
publisher_namespace: EnginesSystem
type_path: filesystem/local/filesystem
container_name: volmanager
ctype: service
persistant: true
conf_self_start: true
last_error: 
memory: '16'
hostname: volmanager
domain_name: 
environments: []
image: engines/fs:alpha
volumes: 
eports: []
repo: na
last_result: |
  b06184ef59759baec2c7bb6a854c9d529cfa47eda9fa9d4e95c8ac27f6da424c
setState: nocontainer
nginxored: false
databases: []
conf_register_site: false
conf_register_dns: true